#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Quiz Jurumiyah - Terminal Interactive Quiz
- Topik berdasarkan Kitab Al-Ajurrumiyah (disederhanakan)
- Bab: Kalam, Kalimah, Ciri-Ciri Isim, Ciri-Ciri Fi'il, Ciri-Ciri Huruf,
       Huruf Jar (pilihan utama), Huruf Qasam.
- 10 soal per topik (pilihan ganda) + penjelasan.
- Menyimpan hasil di results_TIMESTAMP.json

Author: Generated by ChatGPT (GPT-5 Thinking mini)
"""
import random
import json
import datetime
import sys

QUESTION_BANK = {
    "Kalam (الكلام)": [
        {
            "q": "Definisi kalām menurut nahwu (ringkas) adalah:",
            "choices": [
                "Lafaz yang tersusun, memberi faidah sempurna, berdasarkan wad'i (bahasa Arab).",
                "Satu kata yang berdiri sendiri tanpa konteks.",
                "Tulisan di kertas yang bermakna.",
                "Isyarat tangan yang dimengerti."
            ],
            "a": 0,
            "ex": "Kalam menurut nahwu: lafẓ murakkab (lebih dari satu kata), mufīd (mendatangkan faedah sempurna), wad'i (berbahasa Arab)."
        },
        {
            "q": "Mana yang memenuhi syarat kalām?",
            "choices": ["زيدٌ", "زيدٌ قائمٌ", "في البيتِ", "إذا جاء زيدٌ ..."],
            "a": 1,
            "ex": "'زيدٌ قائمٌ' murakkab dan mufīd → kalām. 'زيدٌ' hanya kalimah. 'إذا جاء زيدٌ...' menggantung (tidak mufīd)."
        },
        {
            "q": "Syarat 'lafaz' dalam definisi kalām maksudnya:",
            "choices": [
                "Harus terdengar (diucapkan), bukan hanya tertulis.",
                "Boleh hanya tertulis di kertas.",
                "Bisa berupa isyarat tangan.",
                "Khusus untuk tulisan suci saja."
            ],
            "a": 0,
            "ex": "Lafaz = suara yang keluar dari mulut dan terdengar; definisi nahwu menekankan pengucapan, bukan sekadar tulisan."
        },
        {
            "q": "Mengapa 'إذا جاء زيدٌ...' tidak disebut kalām sempurna?",
            "choices": [
                "Karena susunan salah.",
                "Karena mengandung huruf yang tidak dikenal.",
                "Karena maknanya menggantung; pendengar menunggu kelanjutan.",
                "Karena bukan bahasa Arab."
            ],
            "a": 2,
            "ex": "Jika dimulai dgn حرف شرط seperti إذا, kalimat menjadi syarthiyah dan makna belum sempurna."
        },
        {
            "q": "Manakah yang bukan syarat kalām menurut definisi klasik?",
            "choices": [
                "Lafaz diucapkan",
                "Tersusun minimal dua kata",
                "Mengandung kata kerja (fi'il)",
                "Memberi faedah sempurna"
            ],
            "a": 2,
            "ex": "Kalam bisa berupa jumlah ismiyyah (tanpa fi'il). Jadi 'mengandung fi'il' bukan syarat."
        },
        {
            "q": "Contoh kalām isimiyyah (nominal sentence):",
            "choices": ["ذهبَ زيدٌ", "زيدٌ قائمٌ", "في السوقِ", "لم يأتِ"], 
            "a": 1,
            "ex": "Jumlah ismiyyah: 'زيدٌ قائمٌ' (mubtada' + khabar) — kalām."
        },
        {
            "q": "Kalām harus 'berdasarkan wad'i' maksudnya adalah:",
            "choices": [
                "Berbahasa Arab sesuai ketentuan bahasa.",
                "Ditulis rapi di kertas.",
                "Diucapkan dengan intonasi tinggi.",
                "Hanya untuk kalimat suci."
            ],
            "a": 0,
            "ex": "Wad'i = berdasarkan penetapan bahasa Arab (aturan bahasa). Kalimat dalam bahasa lain tidak disebut kalām menurut ilmu nahwu."
        },
        {
            "q": "Jika seseorang menulis 'زيد' di papan tulis tetapi tidak mengucapkannya, itu disebut:",
            "choices": [
                "Lafaz (lafẓ)",
                "Kalimah (الكلمة)",
                "Kalam (الكلام)",
                "Harf saja"
            ],
            "a": 1,
            "ex": "Teks tertulis bukan lafaz (suara). 'زيد' sebagai satu kata adalah kalimah."
        },
        {
            "q": "Dalam praktikum nahwu, mengapa penting membedakan kalām dan kalimah?",
            "choices": [
                "Agar bisa menerjemahkan ke bahasa lain lebih cepat.",
                "Karena aturan i'rab dan analisis sintaksis bergantung apakah itu kalām (susunan) atau kalimah (tunggal).",
                "Supaya bisa menulis lebih indah.",
                "Agar dapat membuat puisi."
            ],
            "a": 1,
            "ex": "Analisis sintaksis (i'rab) memerlukan identifikasi apakah sebuah unit adalah kalām (kalimat) atau kalimah (kata tunggal)."
        },
        {
            "q": "Kalām yang mengandung huruf syarth (seperti إِذَا) biasanya:",
            "choices": [
                "Langsung mufīd tanpa lanjutan.",
                "Belum sempurna maknanya hingga klausa syarat dipenuhi.",
                "Bukan bahasa Arab.",
                "Harus diakhiri tanda tanya."
            ],
            "a": 1,
            "ex": "Huruf syarth membuat kalam menjadi syarthiyah; pendengar menunggu kelanjutan."
        },
    ],
    "Kalimah (الكلمة)": [
        {
            "q": "Apa itu kalimah dalam nahwu?",
            "choices": [
                "Lafaz tunggal yang memiliki makna (bisa isim/fi'il/harf).",
                "Susunan lebih dari satu kata yang memberi faedah.",
                "Hanya kata kerja saja.",
                "Tulisan tanpa suara."
            ],
            "a": 0,
            "ex": "Kalimah = satu kata (lafẓ tunggal) yang mengandung makna; terbagi menjadi isim, fi'il, dan harf."
        },
        {
            "q": "Kalimah terbagi menjadi berapa golongan utama?",
            "choices": ["2", "3", "4", "5"],
            "a": 1,
            "ex": "Tiga: isim, fi'il, harf."
        },
        {
            "q": "Contoh fi'il (kata kerja):",
            "choices": ["ذهبَ", "كتابٌ", "في", "محمدٌ"],
            "a": 0,
            "ex": "'ذهبَ' adalah kata kerja (fi'il)."
        },
        {
            "q": "'يا' termasuk jenis kalimah apa?",
            "choices": ["Isim", "Fi'il", "Harf (nida')", "Bukan kalimah"],
            "a": 2,
            "ex": "'يا' huruf nida' (huruf panggilan) — masuk kategori harf."
        },
        {
            "q": "Salah satu alasan kalimah tidak selalu menjadi kalam adalah:",
            "choices": [
                "Kalimah kurang diucapkan",
                "Kalimah hanya satu kata sehingga belum membentuk susunan mufīd.",
                "Kalimah tidak bisa ditulis",
                "Kalimah harus huruf saja"
            ],
            "a": 1,
            "ex": "Kalimah tunggal belum tentu membentuk kalam karena tidak memenuhi syarat murakkab."
        },
        {
            "q": "Kata yang menunjukkan tempat seperti 'في' termasuk:",
            "choices": ["Isim", "Fi'il", "Harf jar", "Kalimah tidak"], 
            "a": 2,
            "ex": "'في' adalah huruf jar (preposisi) — kategori harf."
        },
        {
            "q": "Jika sebuah kata ber-tanwīn (كتابٌ), biasanya itu menunjukkan:",
            "choices": ["Isim nakirah", "Isim ma'rifah", "Fi'il", "Harf"], 
            "a": 0,
            "ex": "Tanwīn biasanya menandakan isim nakirah (umum)."
        },
        {
            "q": "'محمدٌ' termasuk contoh...",
            "choices": ["Isim", "Fi'il", "Harf", "Kalimah tidak"], 
            "a": 0,
            "ex": "Muhammad adalah isim (nama)."
        },
        {
            "q": "Harf yang memanggil orang (nida') contohnya:",
            "choices": ["يا", "من", "إن", "ليس"], 
            "a": 0,
            "ex": "'يا' contoh huruf nida'."
        },
        {
            "q": "Kalimah yang menerangkan keadaan/kwalitas sering disebut:",
            "choices": ["Isim sifat (na't)", "Fi'il", "Harf", "Kalam"], 
            "a": 0,
            "ex": "Kata sifat (na't) termasuk kategori isim yang menerangkan isim lain."
        },
    ],
    "Ciri-Ciri Isim (الاسم)": [
        {
            "q": "Salah satu ciri isim: dapat didahului oleh alif-lam (ال). Contoh:",
            "choices": ["الكتاب", "كتبَ", "في", "يا"], 
            "a": 0,
            "ex": "Alif-lam menandakan isim menjadi ma'rifah: الكتاب."
        },
        {
            "q": "Ciri isim: dapat menerima tanwīn. Contoh:",
            "choices": ["كتابٌ", "يكتبُ", "في", "إن"], 
            "a": 0,
            "ex": "Tanwīn biasanya terjadi pada isim nakirah: كتابٌ."
        },
        {
            "q": "Ciri isim: bisa menjadi objek setelah huruf jar (majrūr). Contoh:",
            "choices": ["في البيتِ", "كتبَ الكتابَ", "هل جاءَ؟", "سيذهب"], 
            "a": 0,
            "ex": "Setelah huruf jar 'في', kata berikutnya 'البيتِ' menjadi majrūr (kasrah)."
        },
        {
            "q": "Ciri isim: bisa masuk dalam idaafah (mudāf atau mudāf ilaih). Contoh:",
            "choices": ["كتابُ زيدٍ", "يكتبُ زيدٌ", "في البيتِ", "لَيْسَ"], 
            "a": 0,
            "ex": "Idaafah menunjukkan kepemilikan/penjelasan: كتابُ زيدٍ."
        },
        {
            "q": "Ciri isim: dapat berfungsi sebagai mubtada' atau khabar dalam jumlah ismiyyah. Contoh mubtada':",
            "choices": ["الكتابُ جديدٌ", "كتبَ الطالبُ", "في السوقِ", "لم يأتِ"], 
            "a": 0,
            "ex": "Jumlah ismiyyah: mubtada' 'الكتابُ' + khabar 'جديدٌ'."
        },
        {
            "q": "Ciri isim: dapat berupa nama orang/tempat (ism 'alam). Contoh:",
            "choices": ["مُحَمَّدٌ", "يكتبُ", "في", "ما"], 
            "a": 0,
            "ex": "Ism 'alam seperti مُحَمَّدٌ termasuk isim."
        },
        {
            "q": "Ciri isim: biasanya menunjukkan sesuatu tanpa keterikatan waktu. Contoh benar:",
            "choices": ["كتابٌ (buku)", "ذهبَ (pergi)", "سيقرأ (akan membaca)", "أفعل"], 
            "a": 0,
            "ex": "Isim menunjukkan entitas/konsep; fi'il terikat waktu (masa lalu, kini, masa datang)."
        },
        {
            "q": "Ciri isim: akhir dengan ta' marbūṭah (ة) sering menunjukkan:",
            "choices": ["Isim muannats (feminin)", "Fi'il", "Harf", "Jumlah"], 
            "a": 0,
            "ex": "Ta' marbūṭah sering menandakan isim mu'annats: مدرسة، سيّارة."
        },
        {
            "q": "Ciri isim: dapat berupa dhamir (kata ganti). Contoh dhamir yang termasuk isim:",
            "choices": ["هو، أنا، نحن", "كتب، قرأ", "في، من", "إن، أن"], 
            "a": 0,
            "ex": "Dhamir seperti 'هو' termasuk kelas isim (mabni pada umumnya)."
        },
        {
            "q": "Kenapa penting mengenal ciri-ciri isim sebelum belajar i'rab?",
            "choices": [
                "Supaya bisa mengeja huruf Arab lebih cepat.",
                "Agar bisa mengenali fungsi sintaksis (mubtada', khabar, maf'ul, dsb.) saat menganalisis kalām.",
                "Untuk menulis puisi.",
                "Agar bisa menerjemahkan ke bahasa lain."
            ],
            "a": 1,
            "ex": "Ciri-ciri isim dasar membantu identifikasi unsur kalām saat analisis i'rab."
        },
    ],
    "Ciri-Ciri Fi'il (الفعل)": [
        {
            "q": "Ciri fi'il: menunjukkan waktu (lalu/now/akan). Contoh fi'il madhi:",
            "choices": ["كتبَ", "الكتابُ", "في", "يا"], 
            "a": 0,
            "ex": "'كتبَ' adalah fi'il madhi (masa lampau)."
        },
        {
            "q": "Tanda fi'il mudhari' sering diawali dengan huruf (ya/ta/nun) atau bisa berupa bentuk tanpa prefix; contoh mudhari':",
            "choices": ["يكتبُ", "كتبَ", "اكتبْ", "الكتاب"], 
            "a": 0,
            "ex": "Yaa atau taa di awal sering menandai fi'il mudhari': يكتبُ."
        },
        {
            "q": "Fi'il amr (perintah) contoh:",
            "choices": ["اِذهبْ", "ذهبَ", "يذهبُ", "الكتاب"], 
            "a": 0,
            "ex": "Perintah diawali huruf amr: اِذهبْ."
        },
        {
            "q": "Salah satu ciri fi'il: berubah bentuk sesuai waktu dan subjek. Benar atau salah?",
            "choices": ["Benar", "Salah", "Tergantung kata", "Hanya untuk isim"], 
            "a": 0,
            "ex": "Fi'il berkonjugasi (perubahan untuk masa dan subjek)."
        },
        {
            "q": "Fi'il bisa menjadi maf'ul (objek) dalam kalimat: 'قرأ الطالبُ الكتابَ' → mana fi'il?",
            "choices": ["قرأ", "الطالبُ", "الكتابَ", "في"], 
            "a": 0,
            "ex": "'قرأ' adalah fi'il (kata kerja) yang diikuti fa'il 'الطالبُ' dan maf'ul 'الكتابَ'."
        },
        {
            "q": "Tanda fi'il madhi biasanya berakhiran dengan vokal... (dalam bentuk dasar)",
            "choices": ["dhammah", "fathah", "kasrah", "sukun"], 
            "a": 1,
            "ex": "Dalam bentuk dasar, fi'il madhi sering berakhiran fathah: كتبَ."
        },
        {
            "q": "Fi'il mudhari' yang dimasukkan partikel 'ما' menjadi... (contoh negatif)",
            "choices": ["لم يدخلnya", "لا يذهبُ", "ما يَفعلُ", "ليس"], 
            "a": 2,
            "ex": "Partikel 'ما' bisa meniadakan mudhari' (tergantung konteks): ما يَفعلُ."
        },
        {
            "q": "Perbedaan mendasar: Isim vs Fi'il, yang mana benar?",
            "choices": [
                "Isim terikat waktu, fi'il tidak",
                "Fi'il terikat waktu (masa), isim tidak terikat waktu",
                "Keduanya sama",
                "Hanya harf yang menunjukkan waktu"
            ],
            "a": 1,
            "ex": "Fi'il berkaitan dengan waktu (lampau, kini, akan), isim tidak."
        },
        {
            "q": "Apakah 'كانَ' termasuk fi'il? (kanun 'kāna')",
            "choices": ["Ya (fi'il madhi)", "Tidak (isim)", "Harf saja", "Kata tanya"], 
            "a": 0,
            "ex": "'كانَ' adalah fi'il madhi (dulu/terjadi) yang berfungsi sebagai kata kerja kopula."
        },
        {
            "q": "Fi'il bisa diubah menjadi bentuk pasif; contoh pasif dari 'كتبَ' adalah:",
            "choices": ["كُتِبَ", "يكتبُ", "كتابٌ", "مكتوبٌ"], 
            "a": 0,
            "ex": "Bentuk pasif lampau dari 'كتبَ' adalah 'كُتِبَ'."
        },
    ],
    "Ciri-Ciri Huruf (الحرف)": [
        {
            "q": "Definisi singkat huruf menurut Jurumiyah: 'al-harf' adalah apa?",
            "choices": [
                "Lafaz yang tidak berdiri sendiri maknanya kecuali dengan yang mengikutnya; tidak bisa i'rab (tidak beramal sendiri).",
                "Kata kerja utama dalam kalimat.",
                "Nama orang atau tempat.",
                "Kata yang selalu berakhiran alif."
            ],
            "a": 0,
            "ex": "Huruf tidak memberi makna penuh sendiri; fungsinya menghubungkan/menentukan hubungan antar kata."
        },
        {
            "q": "Contoh huruf yang beramal pada fi'il (menjadikan mansub) adalah:",
            "choices": ["أنَّ", "في", "و", "يا"], 
            "a": 0,
            "ex": "'أنَّ' (dan beberapa huruf lain) adalah huruf nasb yang menyebabkan kata berikutnya mansub (fathah)."
        },
        {
            "q": "Huruf yang tidak beramal (hanya menyambung) contohnya:",
            "choices": ["واو العطف (و)", "إنَّ", "لم", "من"], 
            "a": 0,
            "ex": "و (wau) hanya huruf ‘athf (penghubung) dan tidak mengubah i'rab secara langsung."
        },
        {
            "q": "Huruf yang biasa menyebabkan i'raab jar disebut:",
            "choices": ["Huruf jar", "Huruf nasb", "Huruf jazm", "Huruf isti'naf"], 
            "a": 0,
            "ex": "Huruf jar (preposisi) menjadikan isim setelahnya majrur."
        },
        {
            "q": "Contoh huruf yang menyebabkan jazm (penghentian pada mudhari'):",
            "choices": ["لم", "في", "ال", "يا"], 
            "a": 0,
            "ex": "'لم' menyebabkan fi'il mudhari' berjazm (sukun atau bentuk lain)."
        },
        {
            "q": "Huruf yang mengawali kalimat syarthiyah (seperti jika) termasuk kategori:",
            "choices": ["Harf (huruf) syarth", "Isim", "Fi'il", "Tidak ada"], 
            "a": 0,
            "ex": "Huruf seperti إذا, إنّ, jika berfungsi sebagai huruf syarth (penentu kondisi)."
        },
        {
            "q": "Huruf 'ما' bisa berfungsi sebagai apa? (pilih jawaban paling tepat)",
            "choices": [
                "Bisa sebagai huruf nafi, atau sebagai isim tergantung konteks",
                "Selalu isim",
                "Selalu fi'il",
                "Selalu huruf jar"
            ],
            "a": 0,
            "ex": "'ما' multifungsi: bisa nafi (negasi), bisa isim tanya, dll., tergantung konteks."
        },
        {
            "q": "Mengapa huruf harus dipelajari terpisah dari isim/fi'il?",
            "choices": [
                "Karena huruf mengubah i'rab/arti namun tidak memiliki i'rab sendiri.",
                "Karena huruf selalu panjang.",
                "Agar bisa menulis indah.",
                "Supaya tahu berapa huruf Arab."
            ],
            "a": 0,
            "ex": "Huruf mengatur hubungan dan i'rab kata lain; mempelajarinya memudahkan analisis kalam."
        },
        {
            "q": "Huruf yang biasanya menuntut isim setelahnya mansub, majrur, atau marfu' disebut:",
            "choices": ["Huruf yang beramal", "Huruf yang tidak beramal", "Isim", "Fi'il"], 
            "a": 0,
            "ex": "Huruf yang beramal seperti huruf nasb, jar, jazm mempengaruhi i'rab yang mengikuti."
        },
        {
            "q": "Contoh huruf yang berfungsi untuk penegasan atau pengecualian (seperti 'قد' atau 'بل') termasuk:",
            "choices": ["Huruf 'عمل' khusus (misc particles)", "Isim", "Fi'il", "Alif-lam"], 
            "a": 0,
            "ex": "Beberapa partikel (huruf) memiliki fungsi khusus (penegasan, pengecualian, dsb.)."
        },
    ],
    "Huruf Jar (حروف الجرّ)": [
        {
            "q": "Huruf jar menyebabkan isim setelahnya ber-i'rab:",
            "choices": ["Marfu' (dhammah)", "Majrur (kasrah)", "Mansub (fathah)", "Jazm (sukun)"],
            "a": 1,
            "ex": "Huruf jar (preposisi) menyebabkan isim berikutnya menjadi majrur → kasrah."
        },
        {
            "q": "Manakah contoh huruf jar?",
            "choices": ["من", "هل", "إن", "لم"], 
            "a": 0,
            "ex": "'من' termasuk huruf jar; 'هل' huruf istifham."
        },
        {
            "q": "Huruf jar yang berfungsi menunjukkan arah/tujuan adalah:",
            "choices": ["من", "إلى", "ربّ", "كا"], 
            "a": 1,
            "ex": "إلى berarti 'ke' atau 'hingga'."
        },
        {
            "q": "Huruf jar yang menunjukkan tempat 'di dalam/pada' adalah:",
            "choices": ["على", "في", "رب", "باء"], 
            "a": 1,
            "ex": "في berarti 'di dalam / pada'."
        },
        {
            "q": "Huruf 'باء' (بِ) umumnya bermakna:",
            "choices": ["Dengan / sebab / alat", "Dari", "Ke", "Seperti"], 
            "a": 0,
            "ex": "باء: alat/wasilah (dengan), atau sebab dalam konteks tertentu."
        },
        {
            "q": "Huruf 'كاف' (كـ) berfungsi untuk:",
            "choices": ["Menunjuk kepemilikan", "Tasybih / perbandingan (seperti)", "Menunjuk tempat", "Menunjuk waktu"], 
            "a": 1,
            "ex": "كاف sering dipakai untuk perbandingan: كالرجلِ (seperti lelaki)."
        },
        {
            "q": "Huruf 'ربَّ' biasanya diikuti oleh isim dengan harakat... menurut pola Jurumiyah:",
            "choices": ["Kasrah", "Fathah (sering mengikuti isim nakirah)", "Dhammah", "Sukun"], 
            "a": 1,
            "ex": "ربَّ biasanya diikuti isim nakirah berfathah (aturan khas)."
        },
        {
            "q": "Mana yang benar: setelah 'من' (min) kita menemukan bentuk:",
            "choices": ["Isim majrur", "Fi'il mansub", "Harf", "Isim marfu'"], 
            "a": 0,
            "ex": "Min diikuti oleh isim majrur: من المدرسةِ."
        },
        {
            "q": "Contoh kalimat yang benar memakai huruf jar 'على':",
            "choices": ["على الطاولةِ", "ذهبَ الطالبُ", "الكتابُ جديدٌ", "إن جاء زيدٌ"], 
            "a": 0